commandSplit() method handling multiple spaces
When user passes multiple spaces into the current implementation, it will result in empty arguments and that can cause problems (e.g. JCommander will throw StringIndexOutOfBoundsException, see below for stack trace).
E.g. 
bin/lr-cli.sh deploy -doNotSkipSingleRootDir -app testApp -ver ver1 -servers tomcat7  -schemas 1
will be split into:
bin/lr-cli.sh, deploy, -doNotSkipSingleRootDir, -app, testApp, -ver, ver1, -servers, tomcat7, , -schemas, 1

Result: LiveRebel 2.6.7 CLI will produce such a stack trace:
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(String.java:658)
        at com.beust.jcommander.JCommander.isOption(JCommander.java:340)
        at com.beust.jcommander.JCommander.expandArgs(JCommander.java:320)
        at com.beust.jcommander.JCommander.parse(JCommander.java:246)
        at com.beust.jcommander.JCommander.parse(JCommander.java:229)
        at com.zeroturnaround.liverebel.cli.Main.main(Main.java:60)